### PR TITLE
feat: Add GetIndexes() method to Migrator

### PR DESCRIPTION
**Pull request by newtonmunene99**
This pull request adds the `GetIndexes()` method to the `Migrator` interface/struct. Currently calling this method returns an error "not support" as it is not implemented, please see https://github.com/googleapis/go-gorm-spanner/issues/69

`GetIndexes` retrieves the information from the databases `information_schema.indexes` and `information_schema.index_columns` views and constructs a slice matching gorm's interface i.e. `[]gorm.Index`

### CODE REVIEW

**Comment by olavloite** [comment]
@newtonmunene99 This change seems to have compilation errors. Would you mind taking a look?

**Comment by newtonmunene99** [comment]
> @newtonmunene99 This change seems to have compilation errors. Would you mind taking a look?

Will have a look ✅

**Comment by newtonmunene99** [comment]
Apologies for that, minor syntax typo

**Review by rahul2393 — APPROVED** [review]

**Review by olavloite — CHANGES_REQUESTED** [review]
We should add a test before merging this

**Comment by olavloite** [comment]
Replaced by #112

**Pull request closed without merging**
